export const EMPTY_VALUE = '—'

export const ApiRoutes = {
	auth: {
		login: '/api/v1/auth/login',
		refresh: '/api/v1/auth/refresh',
	},
	users: {
		me: '/api/v1/users/me',
		// default: '/api/v1/users',
		// rolesStats: '/api/v1/users/roles-stats',
		// resetPassword: '/api/v1/users/reset-password',
		// setPassword: '/api/v1/users/set-password',
		// validateEmailChange: '/api/v1/users/validate-email-change',
		// validateConfirmationToken: '/api/v1/users/validate-confirmation-token',
		// byId: (id: string) => `/api/v1/users/${id}`,
	},
	devices: {
		default: '/api/v1/devices',
		// 	batch: '/api/v1/devices/batch',
		// 	labels: '/api/v1/devices/labels',
		// byId: (id: string) => `/api/v1/devices/${id}`,
		// logs: (id: string) => `/api/v1/devices/${id}/logs`,
		// 	performance: (id: string) => `/api/v1/devices/${id}/performance`,
		// },
		// deviceGroups: {
		// 	default: '/api/v1/device-groups',
		// 	byId: (id: string) => `/api/v1/device-groups/${id}`,
	},
	locations: {
		default: '/api/v1/locations',
		// map: '/api/v1/locations/map',
		// search: '/api/v1/locations/search',
		// byId: (id: string) => `/api/v1/locations/${id}`,
		// devices: (id: string) => `/api/v1/locations/${id}/devices`,
		// analyticsSummary: (id: string) => `/api/v1/locations/${id}/analytics/summary`,
		// analyticsDashboardCard: (id: string) => `/api/v1/locations/${id}/analytics/dashboard-card`,
		// analyticsReport: (id: string) => `/api/v1/locations/${id}/analytics/report`,
	},
	// groups: {
	// 	default: '/api/v1/groups',
	// 	byId: (id: string) => `/api/v1/groups/${id}`,
	// },
	// health: {
	// 	default: '/api/v1/health',
	// },
	reports: {
		default: '/api/v1/reports',
		// byId: (id: string) => `/api/v1/reports/${id}`,
		// 	gadgets: (id: string) => `/api/v1/reports/${id}/gadgets`,
		// 	gadgetById: (id: string, gadgetId: string) => `/api/v1/reports/${id}/gadgets/${gadgetId}`,
	},
	// connections: {
	// 	default: '/api/v1/connections',
	// 	batch: '/api/v1/connections/batch',
	// 	byId: (id: string) => `/api/v1/connections/${id}`,
	// },
	// dashboards: {
	// 	reports: '/api/v1/dashboards/reports',
	// 	reportById: (id: string) => `/api/v1/dashboards/reports/${id}`,
	// },
	status: {
		default: '/api/v1/status',
		// location: (id: string) => `/api/v1/status/location/${id}`,
		// device: (id: string) => `/api/v1/status/device/${id}`,
	},
	// integrations: {
	// 	default: '/api/v1/integrations',
	// 	recipients: '/api/v1/integrations/recipients',
	// },
	// organizations: {
	// 	default: '/api/v1/organizations',
	// },
	// notifications: {
	// 	default: '/api/v1/notifications',
	// },
	alerts: {
		default: '/api/v1/alerts',
		// 	anomalyMarks: '/api/v1/alerts/anomaly-marks',
		// 	reportsCsv: '/api/v1/alerts/reports/csv',
		// byId: (id: string) => `/api/v1/alerts/${id}`,
	},
	categories: {
		default: '/api/v1/categories',
		// 	byId: (id: string) => `/api/v1/categories/${id}`,
	},
	// units: {
	// 	default: '/api/v1/units',
	// 	batch: '/api/v1/units/batch',
	// 	data: '/api/v1/units/data',
	// 	profile: '/api/v1/units/profile',
	// 	validateFormula: '/api/v1/units/validate-formula',
	// 	byId: (id: string) => `/api/v1/units/${id}`,
	// 	dataById: (id: string) => `/api/v1/units/${id}/data`,
	// },
	// communication: {
	// 	status: '/api/v1/communication/status',
	// 	write: '/api/v1/communication/write',
	// 	testConnection: '/api/v1/communication/test-connection',
	// },
	// strategies: {
	// 	default: '/api/v1/strategies',
	// 	executionLog: '/api/v1/strategies/execution-log',
	// 	byId: (id: string) => `/api/v1/strategies/${id}`,
	// 	duplicate: (id: string) => `/api/v1/strategies/${id}/duplicate`,
	// },
	// processes: {
	// 	default: '/api/v1/processes',
	// 	byId: (id: string) => `/api/v1/processes/${id}`,
	// 	duplicate: (id: string) => `/api/v1/processes/${id}/duplicate`,
	// 	units: (id: string) => `/api/v1/processes/${id}/units`,
	// 	unitById: (id: string, unitId: string) => `/api/v1/processes/${id}/units/${unitId}`,
	// 	events: (id: string) => `/api/v1/processes/${id}/events`,
	// 	analytics: (id: string) => `/api/v1/processes/${id}/analytics`,
	// 	analyticsLatest: (id: string) => `/api/v1/processes/${id}/analytics/latest`,
	// 	metrics: (id: string) => `/api/v1/processes/${id}/metrics`,
	// 	forecast: (id: string) => `/api/v1/processes/${id}/forecast`,
	// 	forecastLongTerm: (id: string) => `/api/v1/processes/${id}/forecast-long-term`,
	// 	correlations: (id: string) => `/api/v1/processes/${id}/correlations`,
	// 	benchmark: (id: string) => `/api/v1/processes/${id}/benchmark`,
	// 	roi: (id: string) => `/api/v1/processes/${id}/roi`,
	// 	degradation: (id: string) => `/api/v1/processes/${id}/degradation`,
	// 	health: (id: string) => `/api/v1/processes/${id}/health`,
	// 	designComparison: (id: string) => `/api/v1/processes/${id}/design-comparison`,
	// 	diagnostics: (id: string) => `/api/v1/processes/${id}/diagnostics`,
	// 	context: (id: string) => `/api/v1/processes/${id}/context`,
	// 	scenarios: (id: string) => `/api/v1/processes/${id}/scenarios`,
	// 	scenarioById: (id: string, scenarioId: string) => `/api/v1/processes/${id}/scenarios/${scenarioId}`,
	// 	mvBaseline: (id: string) => `/api/v1/processes/${id}/mv-baseline`,
	// 	peerComparison: (id: string) => `/api/v1/processes/${id}/peer-comparison`,
	// 	recommendations: (id: string) => `/api/v1/processes/${id}/recommendations`,
	// 	weather: (id: string) => `/api/v1/processes/${id}/weather`,
	// 	compute: (id: string) => `/api/v1/processes/${id}/compute`,
	// 	aiAnalysis: (id: string) => `/api/v1/processes/${id}/ai-analysis`,
	// 	aiChat: (id: string) => `/api/v1/processes/${id}/ai-chat`,
	// 	backfill: (id: string) => `/api/v1/processes/${id}/backfill`,
	// 	report: (id: string) => `/api/v1/processes/${id}/report`,
	// },
	// mlAnalytics: {
	// 	default: '/api/v1/ml-analytics',
	// },
	// logs: {
	// 	default: '/api/v1/logs',
	// },
	// userLogs: {
	// 	default: '/api/v1/user-logs',
	// 	byId: (id: string) => `/api/v1/user-logs/${id}`,
	// },
}
